### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by jaelim** [pengsun/AOSOLogitBoost#1]
Hello,

I ran into a problem of compiling AOSOLogitBoost_mex.cpp file (same for other mex.cpp files) to produce a working mex binary. Your settings.m parameter definitions seem to be outdated, especially this one: lib2 = 'opencv_core243'; as I have a version opencv 3.0.0 installed on my 0Ubuntu 14.0.4. Even after changing the parameter to this lib2 = 'opencv_core'; a different error was outputted relating to a couple of undefined variables.

So, I decided to bypass your make file, and use my own make command with all dependent files moved into a same folder:
mex CFLAGS="\$CFLAGS -std=c99" -largeArrayDims AOSOLogitBoost_mex.cpp MLData.cpp AOSOLogitBoost.cpp utilCPP.cpp

However, I still have problem. Error message is as follows:
Can you try to update your mex make files for Linux/Ubuntu?

Building with 'g++'.
Error using mex
/tmp/mex_1658646058957428_24571/AOSOLogitBoost_mex.o: In function `train(int, mxArray_tag**, int, mxArray_tag const**)':
AOSOLogitBoost_mex.cpp:(.text+0x504): undefined reference to`cv::Mat::deallocate()'
AOSOLogitBoost_mex.cpp:(.text+0x57d): undefined reference to `cv::fastFree(void*)'
AOSOLogitBoost_mex.cpp:(.text+0x5a4): undefined reference to`cv::Mat::deallocate()'
AOSOLogitBoost_mex.cpp:(.text+0x61d): undefined reference to `cv::fastFree(void*)'
/tmp/mex_1658646058957428_24571/AOSOLogitBoost_mex.o: In function`predict(int, mxArray_tag**, int, mxArray_tag const**)':
AOSOLogitBoost_mex.cpp:(.text+0x821): undefined reference to `cv::Mat::deallocate()'
AOSOLogitBoost_mex.cpp:(.text+0x89a): undefined reference to`cv::fastFree(void_)'
AOSOLogitBoost_mex.cpp:(.text+0x8c1): undefined reference to `cv::Mat::deallocate()'
AOSOLogitBoost_mex.cpp:(.text+0x93a): undefined reference to`cv::fastFree(void_)'
/tmp/mex_1658646058957428_24571/AOSOLogitBoost_mex.o: In function `del(int, mxArray_tag**, int, mxArray_tag const**)':
AOSOLogitBoost_mex.cpp:(.text+0xa7c): undefined reference to`cv::Mat::deallocate()'
AOSOLogitBoost_mex.cpp:(.text+0xadb): undefined reference to `cv::fastFree(void*)'
AOSOLogitBoost_mex.cpp:(.text+0xb03): undefined reference to`cv::Mat::deallocate()'
AOSOLogitBoost_mex.cpp:(.text+0xb62): undefined reference to `cv::fastFree(void*)'
AOSOLogitBoost_mex.cpp:(.text+0xb86): undefined reference to`cv::Mat::deallocate()'
AOSOLogitBoost_mex.cpp:(.text+0xbea): undefined reference to `cv::fastFree(void*)'
AOSOLogitBoost_mex.cpp:(.text+0xc56): undefined reference to`cv::Mat::deallocate()'
AOSOLogitBoost_mex.cpp:(.text+0xcca): undefined reference to `cv::fastFree(void*)'
AOSOLogitBoost_mex.cpp:(.text+0xcf4): undefined reference to`cv::Mat::deallocate()'
AOSOLogitBoost_mex.cpp:(.text+0xd68): undefined reference to `cv::fastFree(void*)'
AOSOLogitBoost_mex.cpp:(.text+0xd92): undefined reference to`cv::Mat::deallocate()'
AOSOLogitBoost_mex.cpp:(.text+0xe06): undefined reference to `cv::fastFree(void*)'
AOSOLogitBoost_mex.cpp:(.text+0xe85): undefined reference to`cv::Mat::deallocate()'
AOSOLogitBoost_mex.cpp:(.text+0xef9): undefined reference to `cv::fastFree(void*)'
AOSOLogitBoost_mex.cpp:(.text+0xf1d): undefined reference to`cv::Mat::deallocate()'
AOSOLogitBoost_mex.cpp:(.text+0xf79): undefined reference to `cv::fastFree(void*)'
/tmp/mex_1658646058957428_24571/AOSOLogitBoost_mex.o: In function`MLData::~MLData()':
AOSOLogitBoost_mex.cpp:(.text._ZN6MLDataD2Ev[_ZN6MLDataD5Ev]+0xd1): undefined reference to `cv::Mat::deallocate()'
AOSOLogitBoost_mex.cpp:(.text._ZN6MLDataD2Ev[_ZN6MLDataD5Ev]+0x144): undefined reference to`cv::fastFree(void_)'
AOSOLogitBoost_mex.cpp:(.text._ZN6MLDataD2Ev[_ZN6MLDataD5Ev]+0x168): undefined reference to `cv::Mat::deallocate()'
AOSOLogitBoost_mex.cpp:(.text._ZN6MLDataD2Ev[_ZN6MLDataD5Ev]+0x1cb): undefined reference to`cv::fastFree(void_)'
/tmp/mex_1658646058957428_24571/MLData.o: In function `MLData::preprocess()':
MLData.cpp:(.text+0x49b): undefined reference to`cv::noArray()'
MLData.cpp:(.text+0x4e4): undefined reference to `cv::Mat::Mat(cv::Mat const&, cv::Range const&, cv::Range const&)'
MLData.cpp:(.text+0x53c): undefined reference to`cv::minMaxIdx(cv::_InputArray const&, double_, double_, int_, int_, cv::_InputArray const&)'
MLData.cpp:(.text+0x560): undefined reference to `cv::Mat::deallocate()'
MLData.cpp:(.text+0x5c1): undefined reference to`cv::fastFree(void_)'
MLData.cpp:(.text+0x5fa): undefined reference to `cv::String::allocate(unsigned long)'
MLData.cpp:(.text+0x636): undefined reference to`cv::error(int, cv::String const&, char const_, char const_, int)'
MLData.cpp:(.text+0x642): undefined reference to `cv::String::deallocate()'
MLData.cpp:(.text+0x875): undefined reference to`cv::Mat::deallocate()'
MLData.cpp:(.text+0x8d6): undefined reference to `cv::fastFree(void_)'
MLData.cpp:(.text+0x8ed): undefined reference to `cv::String::deallocate()'
/tmp/mex_1658646058957428_24571/AOSOLogitBoost.o: In function`AOSOTree::predict(MLData_)':
AOSOLogitBoost.cpp:(.text+0x85f): undefined reference to `cv::Mat::create(int, int const_, int)'
/tmp/mex_1658646058957428_24571/AOSOLogitBoost.o: In function `AOSOLogitBoost::predict(MLData*)':
AOSOLogitBoost.cpp:(.text+0x9ed): undefined reference to`cv::Mat::create(int, int const_, int)'
/tmp/mex_1658646058957428_24571/AOSOLogitBoost.o: In function `AOSOLogitBoost::predict(MLData_, int)':
AOSOLogitBoost.cpp:(.text+0xbc6): undefined reference to `cv::Mat::create(int, int const*, int)'
AOSOLogitBoost.cpp:(.text+0xbeb): undefined reference to`cv::Mat::create(int, int const*, int)'
AOSOLogitBoost.cpp:(.text+0xc0f): undefined reference to `cv::Mat::operator=(cv::Scalar_<double> const&)'
/tmp/mex_1658646058957428_24571/AOSOLogitBoost.o: In function `AOSOTree::split_node(AOSONodegain*, AOSODatagain*)':
AOSOLogitBoost.cpp:(.text+0x2176): undefined reference to`cv::String::allocate(unsigned long)'
AOSOLogitBoost.cpp:(.text+0x21c8): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
AOSOLogitBoost.cpp:(.text+0x21d4): undefined reference to`cv::String::deallocate()'
AOSOLogitBoost.cpp:(.text+0x22ec): undefined reference to `cv::String::deallocate()'
/tmp/mex_1658646058957428_24571/AOSOLogitBoost.o: In function`AOSOLogitBoost::convertToStorTrees()':
AOSOLogitBoost.cpp:(.text+0x31ba): undefined reference to `cv::Mat::deallocate()'
AOSOLogitBoost.cpp:(.text+0x321b): undefined reference to`cv::fastFree(void_)'
AOSOLogitBoost.cpp:(.text+0x3242): undefined reference to `cv::Mat::deallocate()'
AOSOLogitBoost.cpp:(.text+0x32a3): undefined reference to`cv::fastFree(void_)'
AOSOLogitBoost.cpp:(.text+0x32c6): undefined reference to `cv::Mat::deallocate()'
AOSOLogitBoost.cpp:(.text+0x3325): undefined reference to`cv::fastFree(void_)'
AOSOLogitBoost.cpp:(.text+0x33e8): undefined reference to `cv::Mat::operator=(cv::Scalar_<double> const&)'
AOSOLogitBoost.cpp:(.text+0x3466): undefined reference to`cv::Mat::operator=(cv::Scalar_<double> const&)'
AOSOLogitBoost.cpp:(.text+0x34fb): undefined reference to `cv::Mat::operator=(cv::Scalar_<double> const&)'
AOSOLogitBoost.cpp:(.text+0x3591): undefined reference to`cv::Mat::create(int, int const_, int)'
AOSOLogitBoost.cpp:(.text+0x35b3): undefined reference to `cv::Mat::create(int, int const*, int)'
AOSOLogitBoost.cpp:(.text+0x35d5): undefined reference to`cv::Mat::create(int, int const_, int)'
/tmp/mex_1658646058957428_24571/AOSOLogitBoost.o: In function `AOSOLogitBoost::train_init(MLData_)':
AOSOLogitBoost.cpp:(.text+0x38d6): undefined reference to `cv::Mat::create(int, int const*, int)'
AOSOLogitBoost.cpp:(.text+0x38fa): undefined reference to`cv::Mat::operator=(cv::Scalar_<double> const&)'
AOSOLogitBoost.cpp:(.text+0x3933): undefined reference to `cv::Mat::create(int, int const*, int)'
AOSOLogitBoost.cpp:(.text+0x3959): undefined reference to`cv::Mat::create(int, int const_, int)'
AOSOLogitBoost.cpp:(.text+0x397b): undefined reference to `cv::Mat::create(int, int const_, int)'
/tmp/mex_1658646058957428_24571/AOSOLogitBoost.o: In function `cv::Mat_<double>::~Mat_()':
AOSOLogitBoost.cpp:(.text._ZN2cv4Mat_IdED2Ev[_ZN2cv4Mat_IdED5Ev]+0x26): undefined reference to`cv::Mat::deallocate()'
AOSOLogitBoost.cpp:(.text._ZN2cv4Mat_IdED2Ev[_ZN2cv4Mat_IdED5Ev]+0x89): undefined reference to `cv::fastFree(void*)'
/tmp/mex_1658646058957428_24571/AOSOLogitBoost.o: In function`void std::_Destroy_aux<false>::__destroy<StaticStorTree*>(StaticStorTree_, StaticStorTree_)':
AOSOLogitBoost.cpp:(.text._ZNSt12_Destroy_auxILb0EE9__destroyIP14StaticStorTreeEEvT_S4_[_ZNSt12_Destroy_auxILb0EE9__destroyIP14StaticStorTreeEEvT_S4_]+0x55): undefined reference to `cv::Mat::deallocate()'
AOSOLogitBoost.cpp:(.text._ZNSt12_Destroy_auxILb0EE9__destroyIP14StaticStorTreeEEvT_S4_[_ZNSt12_Destroy_auxILb0EE9__destroyIP14StaticStorTreeEEvT_S4_]+0xb4): undefined reference to`cv::fastFree(void_)'
AOSOLogitBoost.cpp:(.text._ZNSt12_Destroy_auxILb0EE9__destroyIP14StaticStorTreeEEvT_S4_[_ZNSt12_Destroy_auxILb0EE9__destroyIP14StaticStorTreeEEvT_S4_]+0xdc): undefined reference to `cv::Mat::deallocate()'
AOSOLogitBoost.cpp:(.text._ZNSt12_Destroy_auxILb0EE9__destroyIP14StaticStorTreeEEvT_S4_[_ZNSt12_Destroy_auxILb0EE9__destroyIP14StaticStorTreeEEvT_S4_]+0x13b): undefined reference to`cv::fastFree(void_)'
AOSOLogitBoost.cpp:(.text._ZNSt12_Destroy_auxILb0EE9__destroyIP14StaticStorTreeEEvT_S4_[_ZNSt12_Destroy_auxILb0EE9__destroyIP14StaticStorTreeEEvT_S4_]+0x15f): undefined reference to
`cv::Mat::deallocate()'
AOSOLogitBoost.cpp:(.text._ZNSt12_Destroy_auxILb0EE9__destroyIP14StaticStorTreeEEvT_S4_[_ZNSt12_Destroy_auxILb0EE9__destroyIP14StaticStorTreeEEvT_S4_]+0x1c3): undefined reference to`cv::fastFree(void_)'
/tmp/mex_1658646058957428_24571/AOSOLogitBoost.o: In function `cv::Mat_<int>::~Mat_()':
AOSOLogitBoost.cpp:(.text._ZN2cv4Mat_IiED2Ev[_ZN2cv4Mat_IiED5Ev]+0x26): undefined reference to`cv::Mat::deallocate()'
AOSOLogitBoost.cpp:(.text._ZN2cv4Mat_IiED2Ev[_ZN2cv4Mat_IiED5Ev]+0x89): undefined reference to `cv::fastFree(void_)'
/tmp/mex_1658646058957428_24571/AOSOLogitBoost.o: In function `std::vector<StaticStorTree, std::allocator<StaticStorTree> >::_M_default_append(unsigned long)':
AOSOLogitBoost.cpp:(.text._ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm[_ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm]+0x398): undefined reference to`cv::Mat::copySize(cv::Mat
const&)'
AOSOLogitBoost.cpp:(.text._ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm[_ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm]+0x49e): undefined reference to `cv::Mat::copySize(cv::Mat
const&)'
AOSOLogitBoost.cpp:(.text._ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm[_ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm]+0x5c3): undefined reference to`cv::Mat::copySize(cv::Mat
const&)'
AOSOLogitBoost.cpp:(.text._ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm[_ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm]+0x86d): undefined reference to `cv::Mat::deallocate()'
AOSOLogitBoost.cpp:(.text._ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm[_ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm]+0x8cb): undefined reference to`cv::fastFree(void_)'
AOSOLogitBoost.cpp:(.text._ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm[_ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm]+0x8f2): undefined reference to `cv::Mat::deallocate()'
AOSOLogitBoost.cpp:(.text._ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm[_ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm]+0x950): undefined reference to`cv::fastFree(void_)'
AOSOLogitBoost.cpp:(.text._ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm[_ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm]+0x973): undefined reference to `cv::Mat::deallocate()'
AOSOLogitBoost.cpp:(.text._ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm[_ZNSt6vectorI14StaticStorTreeSaIS0_EE17_M_default_appendEm]+0x9cf): undefined reference to`cv::fastFree(void_)'
/tmp/mex_1658646058957428_24571/utilCPP.o: In function `set_X(mxArray_tag const_, cv::Mat&)':
utilCPP.cpp:(.text+0xba): undefined reference to `cv::Mat::deallocate()'
utilCPP.cpp:(.text+0x153): undefined reference to`cv::Mat::copySize(cv::Mat const&)'
utilCPP.cpp:(.text+0x1a0): undefined reference to `cv::Mat::deallocate()'
utilCPP.cpp:(.text+0x1fb): undefined reference to`cv::fastFree(void_)'
/tmp/mex_1658646058957428_24571/utilCPP.o: In function `set_Y(mxArray_tag const_, cv::Mat&)':
utilCPP.cpp:(.text+0x2d5): undefined reference to `cv::Mat::deallocate()'
utilCPP.cpp:(.text+0x36e): undefined reference to`cv::Mat::copySize(cv::Mat const&)'
utilCPP.cpp:(.text+0x3bb): undefined reference to `cv::Mat::deallocate()'
utilCPP.cpp:(.text+0x416): undefined reference to`cv::fastFree(void_)'
/tmp/mex_1658646058957428_24571/utilCPP.o: In function `set_Ymc(mxArray_tag const_, cv::Mat&)':
utilCPP.cpp:(.text+0x4f5): undefined reference to `cv::Mat::deallocate()'
utilCPP.cpp:(.text+0x58e): undefined reference to`cv::Mat::copySize(cv::Mat const&)'
utilCPP.cpp:(.text+0x5db): undefined reference to `cv::Mat::deallocate()'
utilCPP.cpp:(.text+0x636): undefined reference to`cv::fastFree(void*)'
/tmp/mex_1658646058957428_24571/utilCPP.o: In function `cvMatDbl_to_mxArray(cv::Mat_<double> const&)':
utilCPP.cpp:(.text+0x803): undefined reference to `cv::MatConstIterator::seek(int const*, bool)'
utilCPP.cpp:(.text+0x898): undefined reference to`cv::MatConstIterator::seek(long, bool)'
utilCPP.cpp:(.text+0x94e): undefined reference to `cv::MatConstIterator::seek(int const*, bool)'
utilCPP.cpp:(.text+0x9ee): undefined reference to`cv::MatConstIterator::lpos() const'
utilCPP.cpp:(.text+0x9fa): undefined reference to `cv::MatConstIterator::lpos() const'
utilCPP.cpp:(.text+0xa48): undefined reference to`cv::MatConstIterator::seek(long, bool)'
/tmp/mex_1658646058957428_24571/utilCPP.o: In function `cvMatInt_to_mxArray(cv::Mat_<int> const&)':
utilCPP.cpp:(.text+0xba5): undefined reference to`cv::MatConstIterator::seek(int const_, bool)'
utilCPP.cpp:(.text+0xc3a): undefined reference to `cv::MatConstIterator::seek(long, bool)'
utilCPP.cpp:(.text+0xcf0): undefined reference to`cv::MatConstIterator::seek(int const_, bool)'
utilCPP.cpp:(.text+0xd90): undefined reference to `cv::MatConstIterator::lpos() const'
utilCPP.cpp:(.text+0xd9c): undefined reference to`cv::MatConstIterator::lpos() const'
utilCPP.cpp:(.text+0xde6): undefined reference to `cv::MatConstIterator::seek(long, bool)'
/tmp/mex_1658646058957428_24571/utilCPP.o: In function`cv::String::String(char const_)':
utilCPP.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x49): undefined reference to `cv::String::allocate(unsigned long)'
/tmp/mex_1658646058957428_24571/utilCPP.o: In function`cv::Mat::~Mat()':
utilCPP.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x25): undefined reference to `cv::Mat::deallocate()'
utilCPP.cpp:(.text._ZN2cv3MatD2Ev[_ZN2cv3MatD5Ev]+0x80): undefined reference to`cv::fastFree(void_)'
collect2: error: ld returned 1 exit status

**Comment by pengsun** [comment]
Hi @jaelim,

Sorry I just saw the message. Yes, I would try to update it and let you know when I'm done.

**Comment by pengsun** [comment]
Hi @jaelim,

I've updated the code to adapt opencv 3. It should work now, closing.
